-- Un renglón por cliente: actividad, recencia y últimos 12 meses.
CREATE OR REPLACE VIEW `{project}.{dataset}.v_clientes_resumen` AS
WITH ventas AS (
  SELECT
    CLIENTE_ID,
    MIN(FECHA) AS PRIMERA_COMPRA,
    MAX(IF(TIPO_DOCTO = 'F', FECHA, NULL)) AS ULTIMA_COMPRA,
    SUM(IF(FECHA >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), IMPORTE_NETO, 0)) AS IMPORTE_12M,
    SUM(IF(FECHA >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), UTILIDAD, 0)) AS UTILIDAD_12M,
    COUNT(DISTINCT IF(TIPO_DOCTO = 'F' AND FECHA >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), DOCTO_VE_ID, NULL)) AS FACTURAS_12M,
    COUNT(DISTINCT IF(TIPO_DOCTO = 'F' AND FECHA >= DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), DATE_TRUNC(FECHA, MONTH), NULL)) AS MESES_ACTIVOS_12M,
    SUM(IF(FECHA >= DATE_SUB(CURRENT_DATE(), INTERVAL 24 MONTH) AND FECHA < DATE_SUB(CURRENT_DATE(), INTERVAL 12 MONTH), IMPORTE_NETO, 0)) AS IMPORTE_12M_ANTERIOR
  FROM `{project}.{dataset}.fact_ventas_articulo`
  GROUP BY CLIENTE_ID
)
SELECT
  c.EMPRESA,
  c.CLIENTE_ID,
  c.NOMBRE AS CLIENTE,
  c.ESTATUS,
  c.VENDEDOR_ID,
  ve.NOMBRE AS VENDEDOR,
  v.PRIMERA_COMPRA,
  v.ULTIMA_COMPRA,
  DATE_DIFF(CURRENT_DATE(), v.ULTIMA_COMPRA, DAY) AS DIAS_SIN_COMPRAR,
  CASE
    WHEN v.ULTIMA_COMPRA IS NULL THEN 'Sin ventas'
    WHEN DATE_DIFF(CURRENT_DATE(), v.ULTIMA_COMPRA, DAY) <= 30 THEN 'Activo'
    WHEN DATE_DIFF(CURRENT_DATE(), v.ULTIMA_COMPRA, DAY) <= 90 THEN 'En riesgo'
    WHEN DATE_DIFF(CURRENT_DATE(), v.ULTIMA_COMPRA, DAY) <= 180 THEN 'Inactivo'
    ELSE 'Perdido'
  END AS SEGMENTO_RECENCIA,
  v.IMPORTE_12M,
  v.UTILIDAD_12M,
  v.FACTURAS_12M,
  v.MESES_ACTIVOS_12M,
  SAFE_DIVIDE(v.IMPORTE_12M, v.FACTURAS_12M) AS TICKET_PROMEDIO_12M,
  v.IMPORTE_12M_ANTERIOR,
  SAFE_DIVIDE(v.IMPORTE_12M - v.IMPORTE_12M_ANTERIOR, v.IMPORTE_12M_ANTERIOR) AS CRECIMIENTO_PCT
FROM `{project}.{dataset}.dim_clientes` c
LEFT JOIN ventas v ON v.CLIENTE_ID = c.CLIENTE_ID
LEFT JOIN `{project}.{dataset}.dim_vendedores` ve ON ve.VENDEDOR_ID = c.VENDEDOR_ID;
