-- Existencia al cierre de cada mes por artículo/almacén (acumulado de deltas
-- de SALDOS_IN sobre el saldo inicial), con rotación sobre la venta del mes.
-- Rellena meses sin movimiento para que el cierre sea continuo.
CREATE OR REPLACE VIEW `{project}.{dataset}.v_inventario_mensual` AS
WITH base AS (
  SELECT
    EMPRESA, PERIODO, ARTICULO_ID, ALMACEN_ID,
    SUM(ENTRADAS_UNIDADES) AS ENTRADAS_UNIDADES,
    SUM(SALIDAS_UNIDADES) AS SALIDAS_UNIDADES,
    SUM(ENTRADAS_COSTO) AS ENTRADAS_COSTO,
    SUM(SALIDAS_COSTO) AS SALIDAS_COSTO,
    LOGICAL_OR(ES_SALDO_INICIAL) AS ES_SALDO_INICIAL
  FROM `{project}.{dataset}.fact_saldos_mensuales`
  GROUP BY 1, 2, 3, 4
),
pares AS (
  SELECT EMPRESA, ARTICULO_ID, ALMACEN_ID, MIN(PERIODO) AS DESDE
  FROM base
  GROUP BY 1, 2, 3
),
meses AS (
  SELECT periodo
  FROM UNNEST(GENERATE_DATE_ARRAY(
    (SELECT MIN(PERIODO) FROM base),
    DATE_TRUNC(CURRENT_DATE(), MONTH),
    INTERVAL 1 MONTH
  )) AS periodo
),
grid AS (
  SELECT p.EMPRESA, p.ARTICULO_ID, p.ALMACEN_ID, m.periodo AS PERIODO
  FROM pares p
  CROSS JOIN meses m
  WHERE m.periodo >= p.DESDE
),
serie AS (
  SELECT
    g.EMPRESA, g.PERIODO, g.ARTICULO_ID, g.ALMACEN_ID,
    COALESCE(b.ENTRADAS_UNIDADES, 0) AS ENTRADAS_UNIDADES,
    COALESCE(b.SALIDAS_UNIDADES, 0) AS SALIDAS_UNIDADES,
    COALESCE(b.ENTRADAS_COSTO, 0) AS ENTRADAS_COSTO,
    COALESCE(b.SALIDAS_COSTO, 0) AS SALIDAS_COSTO,
    COALESCE(b.ES_SALDO_INICIAL, FALSE) AS ES_SALDO_INICIAL,
    SUM(COALESCE(b.ENTRADAS_UNIDADES, 0) - COALESCE(b.SALIDAS_UNIDADES, 0))
      OVER (PARTITION BY g.ARTICULO_ID, g.ALMACEN_ID ORDER BY g.PERIODO) AS EXISTENCIA_FIN_MES,
    SUM(COALESCE(b.ENTRADAS_COSTO, 0) - COALESCE(b.SALIDAS_COSTO, 0))
      OVER (PARTITION BY g.ARTICULO_ID, g.ALMACEN_ID ORDER BY g.PERIODO) AS VALOR_COSTO_FIN_MES
  FROM grid g
  LEFT JOIN base b
    ON b.ARTICULO_ID = g.ARTICULO_ID AND b.ALMACEN_ID = g.ALMACEN_ID AND b.PERIODO = g.PERIODO
),
venta_mes AS (
  SELECT DATE_TRUNC(FECHA, MONTH) AS PERIODO, ARTICULO_ID, ALMACEN_ID, SUM(UNIDADES) AS UNIDADES_VENDIDAS
  FROM `{project}.{dataset}.fact_ventas_articulo`
  GROUP BY 1, 2, 3
)
SELECT
  s.EMPRESA,
  s.PERIODO,
  s.ARTICULO_ID,
  a.NOMBRE AS ARTICULO,
  a.LINEA_ARTICULO_ID,
  l.NOMBRE AS LINEA,
  s.ALMACEN_ID,
  al.NOMBRE AS ALMACEN,
  s.ENTRADAS_UNIDADES,
  s.SALIDAS_UNIDADES,
  s.EXISTENCIA_FIN_MES,
  s.VALOR_COSTO_FIN_MES,
  s.ES_SALDO_INICIAL,
  COALESCE(vm.UNIDADES_VENDIDAS, 0) AS UNIDADES_VENDIDAS,
  SAFE_DIVIDE(COALESCE(vm.UNIDADES_VENDIDAS, 0), NULLIF(s.EXISTENCIA_FIN_MES, 0)) AS ROTACION_MES
FROM serie s
LEFT JOIN venta_mes vm
  ON vm.PERIODO = s.PERIODO AND vm.ARTICULO_ID = s.ARTICULO_ID AND vm.ALMACEN_ID = s.ALMACEN_ID
LEFT JOIN `{project}.{dataset}.dim_articulos` a ON a.ARTICULO_ID = s.ARTICULO_ID
LEFT JOIN `{project}.{dataset}.dim_lineas` l ON l.LINEA_ARTICULO_ID = a.LINEA_ARTICULO_ID
LEFT JOIN `{project}.{dataset}.dim_almacenes` al ON al.ALMACEN_ID = s.ALMACEN_ID;
