-- Último costo de compra por artículo y proveedor predeterminado / lead time.
CREATE OR REPLACE VIEW `{project}.{dataset}.v_ultimo_costo_articulo` AS
WITH ultima AS (
  SELECT
    ARTICULO_ID, PROVEEDOR_ID, FECHA AS FECHA_ULT_COMPRA,
    PRECIO_UNITARIO AS ULTIMO_COSTO, UNIDADES AS UNIDADES_ULT_COMPRA, FOLIO
  FROM `{project}.{dataset}.fact_compras_partidas`
  WHERE TIPO_DOCTO = 'C' AND ESTATUS <> 'C' AND UNIDADES > 0
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ARTICULO_ID ORDER BY FECHA DESC, DOCTO_CM_DET_ID DESC) = 1
),
predet AS (
  SELECT ARTICULO_ID, PROVEEDOR_ID, DIAS_ENTREGA_PROM, FECHA_PRECIO_ULT_COMPRA, NUM_COMPRAS
  FROM `{project}.{dataset}.dim_articulo_proveedor`
  WHERE ES_PROV_PREDET
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ARTICULO_ID ORDER BY PRIORIDAD_COMPRA, PRECIO_COMPRA_ID) = 1
)
SELECT
  a.EMPRESA,
  a.ARTICULO_ID,
  a.NOMBRE AS ARTICULO,
  a.ESTATUS,
  a.LINEA_ARTICULO_ID,
  l.NOMBRE AS LINEA,
  u.PROVEEDOR_ID AS PROVEEDOR_ULT_COMPRA_ID,
  pu.NOMBRE AS PROVEEDOR_ULT_COMPRA,
  u.FECHA_ULT_COMPRA,
  u.ULTIMO_COSTO,
  u.UNIDADES_ULT_COMPRA,
  d.PROVEEDOR_ID AS PROVEEDOR_PREDET_ID,
  pd.NOMBRE AS PROVEEDOR_PREDET,
  d.DIAS_ENTREGA_PROM,
  d.NUM_COMPRAS
FROM `{project}.{dataset}.dim_articulos` a
LEFT JOIN `{project}.{dataset}.dim_lineas` l ON l.LINEA_ARTICULO_ID = a.LINEA_ARTICULO_ID
LEFT JOIN ultima u ON u.ARTICULO_ID = a.ARTICULO_ID
LEFT JOIN `{project}.{dataset}.dim_proveedores` pu ON pu.PROVEEDOR_ID = u.PROVEEDOR_ID
LEFT JOIN predet d ON d.ARTICULO_ID = a.ARTICULO_ID
LEFT JOIN `{project}.{dataset}.dim_proveedores` pd ON pd.PROVEEDOR_ID = d.PROVEEDOR_ID;
